baseurl = "/"
languageCode = "en-us"
theme = "matthewgall"
[pagination]
pagerSize = 5

[params]
  # Site Description
  description = "Thoughts, ideas and dreams of Matthew - personal blog covering technology, development, and life insights."
  keywords = "matthew,gall,matthewgall,family,personal,blog,developer,development,technology"
  author = "Matthew Gall"
  
  # Theme Settings
  brand_name = "Matthew Gall"
  subtitle = "Thoughts, ideas and dreams of Matthew"
  
  # Social Media Links
  social_sharing = true
  
  # SEO and Social Media
  og_image = "/images/og-image.png"
  
  [params.social]
    bluesky = "https://bsky.app/profile/matthewgall.com"
    github = "https://github.com/matthewgall"
    linkedin = "https://linkedin.com/in/matthewgall"
    mastodon = "https://toot.wales/@matthewgall"
    twitter = "https://twitter.com/matthewgall"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "matthewgall"
  site = "matthewgall"

[languages]
  [languages.en]
    languageName = "English"
    title = "Matthew Gall"
    subtitle = "Thoughts, ideas and dreams of Matthew"
    owner = "Matthew Gall"
    keywords = "matthew,gall,matthewgall,family,personal,blog,developer,development"
    copyright = "&copy; Matthew Gall"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"


    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "tools"
        name = "Tools"
        url = "/tools"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"

